import { describe, it, expect } from 'vitest'
import { readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { computeHash, verifyPdf, formatPdfDate } from './pdf-verifier.js'

// Path to the known-good PAdES reference PDF generated by CORTEX
const REFERENCE_PDF = join(
  process.env.HOME || '',
  'Attestto/CORTEX/api/tmp/pades-reference_digitally_signed.pdf',
)

describe('pdf-verifier', () => {
  describe('computeHash', () => {
    it('computes SHA-256 of known input', async () => {
      const encoder = new TextEncoder()
      const buffer = encoder.encode('hello world').buffer
      const hash = await computeHash(buffer)
      // SHA-256 of "hello world"
      expect(hash).toBe('b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9')
    })

    it('produces different hashes for different input', async () => {
      const encoder = new TextEncoder()
      const hash1 = await computeHash(encoder.encode('file1').buffer)
      const hash2 = await computeHash(encoder.encode('file2').buffer)
      expect(hash1).not.toBe(hash2)
    })
  })

  describe('extractSignaturesFromBytes — known-good PAdES reference', () => {
    it('detects the PKCS#7 digital signature', async () => {
      const bytes = await readFile(REFERENCE_PDF)
      const blob = new Blob([bytes], { type: 'application/pdf' })
      const file = new File([blob], 'pades-reference_digitally_signed.pdf')

      const result = await verifyPdf(file)

      expect(result.isPdf).toBe(true)
      expect(result.hash).toBeTruthy()
      expect(result.hash).toHaveLength(64) // SHA-256 hex
      expect(result.signatures.length).toBeGreaterThanOrEqual(1)
    })

    it('extracts signer name', async () => {
      const bytes = await readFile(REFERENCE_PDF)
      const file = new File([bytes], 'pades-reference_digitally_signed.pdf')

      const result = await verifyPdf(file)

      const sig = result.signatures[0]
      expect(sig).toBeDefined()
      expect(sig.name).toBe('EDUARDO ANTONIO CHONGKAN LIOS')
    })

    it('extracts reason', async () => {
      const bytes = await readFile(REFERENCE_PDF)
      const file = new File([bytes], 'pades-reference_digitally_signed.pdf')

      const result = await verifyPdf(file)

      const sig = result.signatures[0]
      expect(sig.reason).toContain('PAdES reference')
    })

    it('extracts location', async () => {
      const bytes = await readFile(REFERENCE_PDF)
      const file = new File([bytes], 'pades-reference_digitally_signed.pdf')

      const result = await verifyPdf(file)

      const sig = result.signatures[0]
      expect(sig.location).toBe('Attestto Platform')
    })

    it('extracts contactInfo', async () => {
      const bytes = await readFile(REFERENCE_PDF)
      const file = new File([bytes], 'pades-reference_digitally_signed.pdf')

      const result = await verifyPdf(file)

      const sig = result.signatures[0]
      expect(sig.contactInfo).toBe('https://attestto.com/verify')
    })

    it('does NOT confuse /Filter /Name with signer /Name', async () => {
      const bytes = await readFile(REFERENCE_PDF)
      const file = new File([bytes], 'pades-reference_digitally_signed.pdf')

      const result = await verifyPdf(file)

      const sig = result.signatures[0]
      // Should be the signer name, NOT "Adobe.PPKLite"
      expect(sig.name).not.toBe('Adobe.PPKLite')
      expect(sig.name).not.toContain('PPKLite')
    })

    it('extracts sign date', async () => {
      const bytes = await readFile(REFERENCE_PDF)
      const file = new File([bytes], 'pades-reference_digitally_signed.pdf')

      const result = await verifyPdf(file)

      const sig = result.signatures[0]
      // signDate should be a parseable date string or null
      // Our reference PDF should have an /M entry
      if (sig.signDate) {
        expect(sig.signDate).toMatch(/^\d{4}/)
      }
    })

    it('sets verification level to detected or parsed', async () => {
      const bytes = await readFile(REFERENCE_PDF)
      const file = new File([bytes], 'pades-reference_digitally_signed.pdf')

      const result = await verifyPdf(file)

      const sig = result.signatures[0]
      // v1 = 'detected' (no certs parsed), v1.5 = 'parsed' (certs extracted from PKCS#7)
      expect(['detected', 'parsed']).toContain(sig.level)
    })

    it('extracts SubFilter from signature dictionary', async () => {
      const bytes = await readFile(REFERENCE_PDF)
      const file = new File([bytes], 'pades-reference_digitally_signed.pdf')

      const result = await verifyPdf(file)

      const sig = result.signatures[0]
      // Our reference PDF uses adbe.pkcs7.detached
      expect(sig.subFilter).toBe('adbe.pkcs7.detached')
    })

    it('has null DID/LEI fields (populated in v2), org may be extracted from cert', async () => {
      const bytes = await readFile(REFERENCE_PDF)
      const file = new File([bytes], 'pades-reference_digitally_signed.pdf')

      const result = await verifyPdf(file)

      const sig = result.signatures[0]
      expect(sig.lei).toBeNull()
      // DID and org may be extracted from cert chain in v1.5, or null
      if (sig.certChain && sig.certChain.certificates.length > 0) {
        expect(sig.level).toBe('parsed')
      }
    })
  })

  describe('forensic audit — security scan', () => {
    it('extracts PDF version from header', async () => {
      const bytes = await readFile(REFERENCE_PDF)
      const file = new File([bytes], 'pades-reference_digitally_signed.pdf')
      const result = await verifyPdf(file)

      expect(result.audit).toBeDefined()
      expect(result.audit!.pdfVersion).toMatch(/^\d+\.\d+$/)
    })

    it('detects no JavaScript in clean PDF', async () => {
      const bytes = await readFile(REFERENCE_PDF)
      const file = new File([bytes], 'pades-reference_digitally_signed.pdf')
      const result = await verifyPdf(file)

      expect(result.audit!.hasJavaScript).toBe(false)
      expect(result.audit!.javaScriptCount).toBe(0)
    })

    it('detects no OpenAction in clean PDF', async () => {
      const bytes = await readFile(REFERENCE_PDF)
      const file = new File([bytes], 'pades-reference_digitally_signed.pdf')
      const result = await verifyPdf(file)

      expect(result.audit!.hasOpenAction).toBe(false)
    })

    it('extracts ByteRange arrays from signatures', async () => {
      const bytes = await readFile(REFERENCE_PDF)
      const file = new File([bytes], 'pades-reference_digitally_signed.pdf')
      const result = await verifyPdf(file)

      expect(result.audit!.byteRanges.length).toBeGreaterThanOrEqual(1)
      const br = result.audit!.byteRanges[0]
      expect(br).toHaveLength(4)
      expect(br[0]).toBe(0) // First segment always starts at 0
      expect(br.every((n) => typeof n === 'number' && n >= 0)).toBe(true)
    })

    it('returns null audit for non-PDF files', async () => {
      const file = new File(['hello world'], 'readme.txt')
      const result = await verifyPdf(file)

      expect(result.audit).toBeNull()
    })
  })

  describe('non-signed PDF', () => {
    it('reports zero signatures for an unsigned PDF', async () => {
      // Create a minimal valid PDF
      const pdfContent = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R>>endobj
xref
0 4
0000000000 65535 f
0000000009 00000 n
0000000058 00000 n
0000000115 00000 n
trailer<</Size 4/Root 1 0 R>>
startxref
190
%%EOF`
      const file = new File([pdfContent], 'unsigned.pdf')
      const result = await verifyPdf(file)

      expect(result.isPdf).toBe(true)
      expect(result.signatures).toHaveLength(0)
    })
  })

  describe('non-PDF file', () => {
    it('returns hash but no signatures for non-PDF', async () => {
      const file = new File(['hello world'], 'readme.txt')
      const result = await verifyPdf(file)

      expect(result.isPdf).toBe(false)
      expect(result.hash).toBeTruthy()
      expect(result.signatures).toHaveLength(0)
      expect(result.metadata).toBeNull()
    })
  })

  describe('formatPdfDate', () => {
    it('parses standard D: prefixed date', () => {
      const result = formatPdfDate('D:20260411093000')
      expect(result).toBe('2026-04-11T09:30:00.000Z')
    })

    it('parses date without D: prefix', () => {
      const result = formatPdfDate('20260101120000')
      expect(result).toBe('2026-01-01T12:00:00.000Z')
    })

    it('parses partial date (year+month only)', () => {
      const result = formatPdfDate('D:202604')
      expect(result).toBe('2026-04-01T00:00:00.000Z')
    })

    it('parses year-only date', () => {
      const result = formatPdfDate('D:2026')
      expect(result).toBe('2026-01-01T00:00:00.000Z')
    })

    it('returns null for empty string', () => {
      expect(formatPdfDate('')).toBeNull()
    })

    it('returns raw string for unparseable date', () => {
      // An invalid date that causes Date constructor to fail
      const result = formatPdfDate('D:notadate')
      expect(result).toBeTruthy() // returns the raw string, not null
    })
  })

  describe('forensic audit — synthetic PDFs', () => {
    it('detects JavaScript in PDF', async () => {
      const pdf = `%PDF-1.7
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R>>endobj
4 0 obj<</JS (app.alert\\('hello'\\))>>endobj
5 0 obj<</JavaScript (more code)>>endobj
%%EOF`
      const file = new File([pdf], 'js-pdf.pdf')
      const result = await verifyPdf(file)

      expect(result.audit!.hasJavaScript).toBe(true)
      expect(result.audit!.javaScriptCount).toBe(2)
    })

    it('detects encrypted PDF (AES-256)', async () => {
      const pdf = `%PDF-2.0
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R>>endobj
4 0 obj<</Encrypt 5 0 R>>endobj
5 0 obj<</Filter /Standard /V 5 /AESV3 true>>endobj
%%EOF`
      const file = new File([pdf], 'encrypted.pdf')
      const result = await verifyPdf(file)

      expect(result.audit!.encrypted).toBe(true)
      expect(result.audit!.encryptionAlgorithm).toBe('AES-256')
    })

    it('detects encrypted PDF (RC4)', async () => {
      const pdf = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R>>endobj
4 0 obj<</Encrypt 5 0 R>>endobj
5 0 obj<</Filter /Standard /V 1 >>endobj
%%EOF`
      const file = new File([pdf], 'rc4.pdf')
      const result = await verifyPdf(file)

      expect(result.audit!.encrypted).toBe(true)
      expect(result.audit!.encryptionAlgorithm).toBe('RC4')
    })

    it('detects OpenAction', async () => {
      const pdf = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R /OpenAction 4 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R>>endobj
4 0 obj<</S/JavaScript /JS (app.alert)>>endobj
%%EOF`
      const file = new File([pdf], 'openaction.pdf')
      const result = await verifyPdf(file)

      expect(result.audit!.hasOpenAction).toBe(true)
      expect(result.audit!.hasJavaScript).toBe(true)
    })

    it('detects embedded files', async () => {
      const pdf = `%PDF-1.7
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R>>endobj
4 0 obj<</Type /EmbeddedFile /Subtype /application#2Fpdf>>endobj
5 0 obj<</Type /EmbeddedFile /Subtype /text#2Fplain>>endobj
%%EOF`
      const file = new File([pdf], 'embedded.pdf')
      const result = await verifyPdf(file)

      expect(result.audit!.embeddedFileCount).toBe(2)
    })

    it('detects external links', async () => {
      const pdf = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R>>endobj
4 0 obj<</S/URI /URI (https://evil.com)>>endobj
%%EOF`
      const file = new File([pdf], 'links.pdf')
      const result = await verifyPdf(file)

      expect(result.audit!.externalLinkCount).toBe(1)
    })

    it('detects LTV data (DSS dictionary)', async () => {
      const pdf = `%PDF-1.7
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R>>endobj
4 0 obj<</DSS <</Certs [5 0 R]>> >>endobj
%%EOF`
      const file = new File([pdf], 'ltv.pdf')
      const result = await verifyPdf(file)

      expect(result.audit!.hasLtvData).toBe(true)
    })

    it('detects linearized PDF', async () => {
      const pdf = `%PDF-1.4
1 0 obj<</Linearized 1>>endobj
2 0 obj<</Type/Catalog/Pages 3 0 R>>endobj
3 0 obj<</Type/Pages/Kids[4 0 R]/Count 1>>endobj
4 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 3 0 R>>endobj
%%EOF`
      const file = new File([pdf], 'linearized.pdf')
      const result = await verifyPdf(file)

      expect(result.audit!.linearized).toBe(true)
    })

    it('reports clean audit for minimal safe PDF', async () => {
      const pdf = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R>>endobj
%%EOF`
      const file = new File([pdf], 'clean.pdf')
      const result = await verifyPdf(file)

      expect(result.audit!.hasJavaScript).toBe(false)
      expect(result.audit!.hasOpenAction).toBe(false)
      expect(result.audit!.encrypted).toBe(false)
      expect(result.audit!.embeddedFileCount).toBe(0)
      expect(result.audit!.externalLinkCount).toBe(0)
      expect(result.audit!.hasLtvData).toBe(false)
      expect(result.audit!.linearized).toBe(false)
      expect(result.audit!.pdfVersion).toBe('1.4')
    })

    it('counts pages correctly', async () => {
      // 3 /Type /Page entries (not /Pages)
      const pdf = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R 4 0 R 5 0 R]/Count 3>>endobj
3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R>>endobj
4 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R>>endobj
5 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R>>endobj
%%EOF`
      const file = new File([pdf], 'multipage.pdf')
      const result = await verifyPdf(file)

      expect(result.audit!.pageCount).toBe(3)
    })

    it('extracts PDF version 2.0', async () => {
      const pdf = `%PDF-2.0
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R>>endobj
%%EOF`
      const file = new File([pdf], 'v2.pdf')
      const result = await verifyPdf(file)

      expect(result.audit!.pdfVersion).toBe('2.0')
    })
  })

  describe('computeHash edge cases', () => {
    it('handles empty buffer', async () => {
      const hash = await computeHash(new ArrayBuffer(0))
      // SHA-256 of empty input
      expect(hash).toBe('e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855')
    })

    it('produces 64-character hex string', async () => {
      const hash = await computeHash(new TextEncoder().encode('test').buffer)
      expect(hash).toHaveLength(64)
      expect(hash).toMatch(/^[0-9a-f]{64}$/)
    })
  })

  describe('verifyPdf edge cases', () => {
    it('handles empty PDF file', async () => {
      const file = new File([''], 'empty.pdf')
      const result = await verifyPdf(file)

      expect(result.isPdf).toBe(true) // name ends in .pdf
      expect(result.signatures).toHaveLength(0)
      expect(result.audit).toBeDefined()
    })

    it('handles binary garbage as PDF', async () => {
      const garbage = new Uint8Array(1024)
      for (let i = 0; i < 1024; i++) garbage[i] = i % 256
      const file = new File([garbage], 'garbage.pdf')
      const result = await verifyPdf(file)

      expect(result.isPdf).toBe(true)
      expect(result.signatures).toHaveLength(0)
      expect(result.hash).toHaveLength(64)
    })

    it('returns correct fileName and fileSize', async () => {
      const content = 'test content for size check'
      const file = new File([content], 'test-doc.pdf')
      const result = await verifyPdf(file)

      expect(result.fileName).toBe('test-doc.pdf')
      expect(result.fileSize).toBe(content.length)
    })

    it('metadata is null when pdfjs is not available (Node env)', async () => {
      const pdf = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R>>endobj
%%EOF`
      const file = new File([pdf], 'nopdfjs.pdf')
      const result = await verifyPdf(file)

      // In Node tests, pdfjs CDN is not available → metadata stays null
      expect(result.metadata).toBeNull()
    })
  })
})
